# Generated by Django 4.0 on 2022-03-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lion', '0002_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default='', max_length=60),
        ),
    ]
