# Generated by Django 4.0 on 2022-03-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lion', '0003_alter_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
